import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import req from "../utils/req";

export default function Home({ results }) {
  return (
    <div className="">
      <Head>
        <title>Hulu 2.0 | by Adel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Result results={results} />

      {/* The main - results */}
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const genre = ctx.query.genre;

  const res = await axios.get(
    `https://api.themoviedb.org/3${req[genre]?.url || req.fetchTrending.url}`
  );

  return {
    props: {
      results: res.data,
    },
  };
};
